<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\BaseController;
use App\Models\Resume;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ResumeController extends BaseController
{
    /**
     * @var ResumeSkillController
     */
    private $resumeSkillController;

    public function __construct(
        ResumeSkillController $resumeSkillController
    )
    {
        $this->resumeSkillController = $resumeSkillController;

        parent::__construct();
    }

    public function setModel()
    {
        // TODO: Implement setModel() method.
        $this->model = new Resume();
    }

    public function getMyResume()
    {
        $userId = Auth::id();

        $resume = $this->query->where(["user_id" => $userId])
            ->with(["skills", "location"])->first();

        return response()->json($resume);
    }

    public function update(Request $request, $id)
    {
        $resume = $this->query->where("id", $id)->first();
        $newIds = $request->skills;

        $this->resumeSkillController->updateArray($resume, $newIds);

        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
}
